import { SkillDetailMap } from './skill-detail-types';

export const skillDetailsEn: SkillDetailMap = {
  ask: {
    title: 'Ask',
    command: '/cf:ask',
    category: 'Consultation',
    summary: 'Evidence-backed Q&A for project behavior, source code, specs, docs, configuration, dependencies, and external technical topics.',
    when: ['You need to understand how something works in the current system.', 'You need a source-backed answer before planning or changing code.', 'The repo may not have enough information and current external docs may be needed.'],
    flow: [['Classify', 'Identify whether the question is about code behavior, config, specs, dependencies, workflow, or external knowledge.'], ['Scout', 'Read README, docs, specs, code, config, tests, and package metadata before making claims.'], ['Research', 'Use external/current sources only when repo evidence is missing or version-sensitive.'], ['Answer', 'Separate confirmed source facts from inferences and cite evidence.'], ['Ask back', 'Ask one focused question only when the answer would otherwise be misleading.']],
    output: 'A direct answer with evidence, confidence, gaps, and a next step when useful.',
    avoid: 'Do not implement, scaffold, edit product code, generate specs, or treat unanswered facts as confirmed.',
    next: '/cf:brainstorm, /cf:specs, /cf:docs, or /cf:debug depending on the answer',
  },
  brainstorm: {
    title: 'Brainstorm',
    command: '/cf:brainstorm',
    category: 'Discovery',
    summary: 'Scout-first ideation before a spec exists. It turns raw intent into spec-ready decisions without writing implementation code.',
    when: ['The request is vague or broad.', 'Architecture choices are still open.', 'You need scope gates, risks, or tradeoffs before committing to a spec.'],
    flow: [['Scout', 'Inspect the repo or relevant context first.'], ['Frame', 'Name the problem, user value, constraints, non-goals, and risks.'], ['Compare', 'Evaluate simple architecture options and tradeoffs.'], ['Decide', 'Produce spec-ready decisions and open questions.'], ['Handoff', 'Move to specs only after the direction is clear.']],
    output: 'A focused product and architecture direction ready for `/cf:specs`.',
    avoid: 'Do not use it to write code, create scaffolds, or mark implementation choices as final without approval.',
    next: '/cf:specs',
  },
  specs: {
    title: 'Specs',
    command: '/cf:specs',
    category: 'Specification',
    summary: 'Creates a reviewed process-first plan with flat executable tasks and human decisions at C1 and C2.',
    when: ['The direction is clear enough to become requirements.', 'You need task files before coding.', 'The feature needs traceable scope and evidence gates.'],
    flow: [['C1', 'Confirm outcome, scope, exclusions, constraints, and unresolved choices.'], ['Evidence', 'Record findings needed for the decision.'], ['Plan', 'Write plan.md with acceptance criteria and boundaries.'], ['Tasks', 'Create flat task-NN files with ownership, dependencies, and proof commands.'], ['C2', 'Present material review findings for a human decision.']],
    output: 'A reviewed `plan.md` with flat `task-NN-*.md` files, ready for a new explicit develop invocation.',
    avoid: 'Do not use specs as decoration after code is already guessed. The spec should constrain implementation.',
    next: '/cf:develop',
  },
  develop: {
    title: 'Develop',
    command: '/cf:develop',
    category: 'Implementation',
    summary: 'Implements approved task packets with scope fidelity, task-aware inspection, verification, review, and state sync.',
    when: ['A spec or task packet is approved.', 'You want one task implemented safely.', 'The task has completion criteria and evidence expectations.'],
    flow: [['Load', 'Open plan.md and select one unblocked flat task.'], ['Extract', 'Read outcome, ownership, dependencies, acceptance, and proof commands.'], ['Scout', 'Trace real entrypoints, callers, patterns, and blast radius.'], ['Implement', 'Change only the active task boundary unless a justified scope escape is required.'], ['Verify', 'Run the exact planned command and capture current output.'], ['Receipt', 'The controller updates the single Status and final inline Receipt.']],
    output: 'Reachable production code plus task evidence and synchronized state.',
    avoid: 'Do not use it before spec approval or to silently replace named technologies with placeholders.',
    next: '/cf:test and /cf:code-review',
  },
  test: {
    title: 'Test',
    command: '/cf:test',
    category: 'Verification',
    summary: 'Runs real verification and returns a concrete verdict instead of treating green-looking commands as proof.',
    when: ['Implementation changed behavior.', 'You need blast-radius, full-suite, spec-aware, or UI verification.', 'A task needs evidence before it can be done.'],
    flow: [['Detect', 'Find test runner and relevant commands.'], ['Scope', 'Choose blast-radius, full-suite, spec-aware, or UI mode.'], ['Execute', 'Run real lint, type, build, test, or UI checks.'], ['Compare', 'Match results to requirements, design contracts, evidence, and reachability.'], ['Verdict', 'Return PASS, FAIL, PARTIAL, or NO_TESTS with next action.']],
    output: 'A test verdict with commands, outcomes, failures, coverage, and reachability notes when relevant.',
    avoid: 'Never treat NO_TESTS, skipped tests, weakened assertions, or zero executed tests as pass.',
    next: '/cf:code-review',
  },
  'code-review': {
    title: 'Code Review',
    command: '/cf:code-review',
    category: 'Review',
    summary: 'Findings-first review for spec compliance, code quality, security, regressions, and contract drift.',
    when: ['A diff is ready for review.', 'You need an adversarial pass before marking work done.', 'A PR, commit, path, or feature scope needs risk analysis.'],
    flow: [['Target', 'Load pending diff, commit, PR, path, or feature scope.'], ['Spec compliance', 'Check missing requirements, extras, wrong runtime choices, and unverified claims.'], ['Code quality', 'Review YAGNI, KISS, DRY, boundaries, naming, and tests.'], ['Adversarial pass', 'Look for security holes, races, edge cases, and regressions.'], ['Score', 'Return pass/fail with severity-ordered findings.']],
    output: 'A blocking review report. Critical findings prevent completion.',
    avoid: 'Do not use it as a summary-only polish step. It should try to break the change.',
    next: '/cf:sync after fixes and clean verification',
  },
  sync: {
    title: 'Sync',
    command: '/cf:sync',
    category: 'State',
    summary: 'Synchronizes observed process-first task Status and inline Receipts without inventing proof.',
    when: ['A task Status must reflect fresh proof.', 'A task Receipt is stale or incomplete.', 'You need a surgical audit of plan and flat task state.'],
    flow: [['Resolve', 'Identify the feature, flat task, observed state, and exact proof command.'], ['Inspect', 'Read plan.md, the task Status, and final inline Receipt.'], ['Proof gate', 'Reject done without current runtime-derived proof.'], ['Sync', 'Update only the observed Status and canonical Receipt.'], ['Audit', 'Report mismatches without fabricating approval or execution.']],
    output: 'A synchronized flat task with one Status and one current inline Receipt.',
    avoid: 'Do not mark done from chat memory or without evidence in the task file.',
    next: 'Docs checkpoint or next unblocked task',
  },
  debug: {
    title: 'Debug',
    command: '/cf:debug',
    category: 'Diagnosis',
    summary: 'Adaptive-depth, diagnostic-only root-cause workflow for local failures and complex incidents.',
    when: ['Root cause is unknown.', 'A test, build, CI job, UI flow, or production behavior fails.', 'You need evidence before changing code.'],
    flow: [['Scout', 'Map affected files, callers, runtime, config, tests, and recent changes.'], ['Evidence', 'Capture the failing baseline; add a correlated timeline for deep incidents.'], ['Eliminate', 'Test competing causes and preserve why each candidate remains or is removed.'], ['Trace', 'Separate trigger, root cause, and contributing factors back to the earliest owned invariant.'], ['Handoff', 'Define blast radius, verification, side effects, and recurrence-prevention gaps.']],
    output: 'An evidence-backed diagnosis and prevention-aware proof plan ready for `/cf:fix`.',
    avoid: 'Do not edit product code while diagnosing except temporary instrumentation that is removed before handoff.',
    next: '/cf:fix',
  },
  fix: {
    title: 'Fix',
    command: '/cf:fix',
    category: 'Repair',
    summary: 'Adaptive, evidence-backed repair after diagnosis, from quick local fixes to bounded incident work.',
    when: ['A root cause has been identified.', 'A bug needs a safe cause-aligned repair.', 'A production incident needs staged regression proof.'],
    flow: [['Evidence', 'Start from a completed debug contract or diagnose first.'], ['Bound', 'For non-trivial work, state outcome, constraints, non-goals, and acceptance.'], ['Route', 'Use a direct repair or post-diagnosis research, brainstorm, and planning only when needed.'], ['Fix', 'Apply the real repair, not a symptom mask.'], ['Verify', 'Re-run reproduction, blast-radius checks, and prevention proof.']],
    output: 'A bounded repair with before/after proof and explicit residual risk.',
    avoid: 'Do not use it for speculative refactors, feature work, or a symptom-only patch.',
    next: '/cf:test and /cf:code-review',
  },
  docs: {
    title: 'Docs',
    command: '/cf:docs',
    category: 'Documentation',
    summary: 'Creates, refreshes, summarizes, or reconstructs project documentation from source code.',
    when: ['Docs are missing or stale.', 'A code change affects architecture, commands, deployment, or onboarding.', 'A legacy system needs source-backed as-is documentation.'],
    flow: [['Mode', 'Choose init, update, summarize, or reconstruct.'], ['Scout', 'Read source, config, commands, architecture, and docs root.'], ['Write', 'Update living docs or build docs/as-is for a bounded scope.'], ['Uncertainty', 'Track assumptions, unknowns, and evidence.'], ['Validate', 'Run docs validators before handoff.']],
    output: 'Documentation grounded in current source behavior.',
    avoid: 'Do not invent architecture claims that cannot be backed by files, commands, or runtime evidence.',
    next: '/cf:specs for modernization work, or release handoff',
  },
  scout: {
    title: 'Scout',
    command: '/cf:scout',
    category: 'Discovery',
    summary: 'Fast codebase discovery for file finding, task context, entrypoints, call paths, and blast radius.',
    when: ['Relevant files are unclear.', 'A task spans multiple directories.', 'Debugging, implementation, or review needs scoped context.'],
    flow: [['Scope gate', 'Avoid root-wide scans and no-scan paths.'], ['Fast path', 'Use local search and targeted reads for focused scopes.'], ['Delegate', 'Use Explore only with user permission, runtime support, and independent scopes.'], ['Aggregate', 'Return files, call paths, integration points, risks, and next steps.']],
    output: 'A compact context map for safer follow-up work.',
    avoid: 'Do not scan secrets, build outputs, node_modules, .git, or the entire repo when a bounded scope is enough.',
    next: 'The smallest skill that fits the discovered task',
  },
  git: {
    title: 'Git',
    command: '/cf:git',
    category: 'Release',
    summary: 'Safe branch, commit, push, PR, finish, and worktree operations with secret scanning and focused commits.',
    when: ['Verified changes are ready to commit or publish.', 'You need a focused conventional commit.', 'Parallel work needs an isolated worktree.'],
    flow: [['Status', 'Inspect branch, staged diff, unstaged diff, and intended action.'], ['Secret scan', 'Refuse commits containing keys, tokens, passwords, or credentials.'], ['Split', 'Keep commits focused and conventional when needed.'], ['Publish', 'Commit, push, or open PR safely.'], ['Finish', 'Offer merge, PR, keep, or discard choices after verification.']],
    output: 'Clean version-control history without leaking secrets or overwriting unrelated work.',
    avoid: 'Do not force-push, delete worktrees, or discard changes without explicit user confirmation.',
    next: 'Push, PR, or branch finish flow',
  },
};
