import { SkillDetailMap } from './skill-detail-types';

export const skillDetailsVi: SkillDetailMap = {
  ask: {
    title: 'Ask',
    command: '/cf:ask',
    category: 'Consultation',
    summary: 'Skill hỏi đáp có evidence cho source code, docs, specs, config, dependencies, workflow, và thông tin kỹ thuật bên ngoài.',
    when: ['Cần hiểu một luồng hoặc hành vi trong hệ thống hiện tại.', 'Cần câu trả lời có bằng chứng trước khi plan hoặc sửa code.', 'Source trong repo có thể chưa đủ và cần đối chiếu docs/internet hiện tại.'],
    flow: [['Classify', 'Xác định câu hỏi thuộc code behavior, config, specs, dependencies, workflow, hay external knowledge.'], ['Scout', 'Đọc README, docs, specs, code, config, tests, và package metadata trước khi kết luận.'], ['Research', 'Chỉ dùng external/current sources khi repo thiếu bằng chứng hoặc topic phụ thuộc version.'], ['Answer', 'Tách facts đã confirm từ source với inference và cite evidence.'], ['Ask back', 'Chỉ hỏi lại 1 câu tập trung khi nếu trả lời ngay sẽ dễ sai.']],
    output: 'Câu trả lời trực tiếp kèm evidence, confidence, gaps, và next step khi cần.',
    avoid: 'Không implement, scaffold, sửa product code, tạo spec, hoặc xem inference như fact đã confirm.',
    next: '/cf:brainstorm, /cf:specs, /cf:docs, hoặc /cf:debug tùy kết quả trả lời',
  },
  brainstorm: {
    title: 'Brainstorm',
    command: '/cf:brainstorm',
    category: 'Discovery',
    summary: 'Ideation scout-first trước khi có spec. Skill này biến intent thô thành quyết định đủ sẵn sàng cho spec mà không viết code implementation.',
    when: ['Request còn mơ hồ hoặc quá rộng.', 'Architecture choice vẫn đang mở.', 'Cần scope gate, risk, hoặc tradeoff trước khi commit vào spec.'],
    flow: [['Scout', 'Inspect repo hoặc context liên quan trước.'], ['Frame', 'Gọi tên problem, user value, constraints, non-goals, và risks.'], ['Compare', 'So sánh architecture options đơn giản và tradeoffs.'], ['Decide', 'Tạo decisions đủ sẵn sàng cho spec và open questions.'], ['Handoff', 'Chỉ chuyển sang specs khi hướng đã rõ.']],
    output: 'Hướng product và architecture tập trung, sẵn sàng cho `/cf:specs`.',
    avoid: 'Không dùng để viết code, scaffold, hoặc chốt implementation choice khi chưa approve.',
    next: '/cf:specs',
  },
  specs: {
    title: 'Specs',
    command: '/cf:specs',
    category: 'Specification',
    summary: 'Tạo plan process-first đã review, flat executable tasks, và quyết định của user tại C1/C2.',
    when: ['Hướng đã đủ rõ để thành requirements.', 'Cần task files trước khi code.', 'Feature cần traceable scope và evidence gates.'],
    flow: [['C1', 'Xác nhận outcome, scope, exclusions, constraints và lựa chọn chưa giải quyết.'], ['Evidence', 'Ghi findings cần cho quyết định.'], ['Plan', 'Viết plan.md với acceptance criteria và boundaries.'], ['Tasks', 'Tạo flat task-NN có ownership, dependencies và proof command.'], ['C2', 'Đưa material review findings cho user quyết định.']],
    output: '`plan.md` đã review cùng flat `task-NN-*.md`, sẵn sàng cho invocation develop mới.',
    avoid: 'Không dùng spec như tài liệu trang trí sau khi code đã đoán xong. Spec phải constrain implementation.',
    next: '/cf:develop',
  },
  develop: {
    title: 'Develop',
    command: '/cf:develop',
    category: 'Implementation',
    summary: 'Implement approved task packets với scope fidelity, task-aware inspection, verification, review, và state sync.',
    when: ['Spec hoặc task packet đã approve.', 'Muốn implement một task an toàn.', 'Task có completion criteria và evidence expectations.'],
    flow: [['Load', 'Mở plan.md và chọn một flat task chưa bị block.'], ['Extract', 'Đọc outcome, ownership, dependencies, acceptance và proof command.'], ['Scout', 'Trace entrypoints thật, callers, patterns và blast radius.'], ['Implement', 'Chỉ sửa active task boundary trừ khi có scope escape hợp lý.'], ['Verify', 'Chạy exact planned command và lấy current output.'], ['Receipt', 'Controller cập nhật Status duy nhất và final inline Receipt.']],
    output: 'Production code reachable thật, kèm task evidence và synchronized state.',
    avoid: 'Không dùng trước spec approval hoặc để âm thầm thay named technology bằng placeholder.',
    next: '/cf:test và /cf:code-review',
  },
  test: {
    title: 'Test',
    command: '/cf:test',
    category: 'Verification',
    summary: 'Chạy verification thật và trả verdict cụ thể, không xem command xanh bề mặt là proof.',
    when: ['Implementation đổi behavior.', 'Cần blast-radius, full-suite, spec-aware, hoặc UI verification.', 'Task cần evidence trước khi done.'],
    flow: [['Detect', 'Tìm test runner và commands liên quan.'], ['Scope', 'Chọn blast-radius, full-suite, spec-aware, hoặc UI mode.'], ['Execute', 'Chạy lint, type, build, test, hoặc UI checks thật.'], ['Compare', 'So kết quả với requirements, design contracts, evidence, reachability.'], ['Verdict', 'Trả PASS, FAIL, PARTIAL, hoặc NO_TESTS cùng next action.']],
    output: 'Test verdict có commands, outcomes, failures, coverage, và reachability notes khi cần.',
    avoid: 'Không bao giờ xem NO_TESTS, skipped tests, assertion bị làm yếu, hoặc zero executed tests là pass.',
    next: '/cf:code-review',
  },
  'code-review': {
    title: 'Code Review',
    command: '/cf:code-review',
    category: 'Review',
    summary: 'Review findings-first cho spec compliance, code quality, security, regressions, và contract drift.',
    when: ['Diff đã sẵn sàng để review.', 'Cần adversarial pass trước khi mark done.', 'PR, commit, path, hoặc feature scope cần risk analysis.'],
    flow: [['Target', 'Load pending diff, commit, PR, path, hoặc feature scope.'], ['Spec compliance', 'Bắt thiếu requirement, scope dư, runtime choice sai, claim chưa verify.'], ['Code quality', 'Review YAGNI, KISS, DRY, boundaries, naming, tests.'], ['Adversarial pass', 'Tìm security holes, races, edge cases, regressions.'], ['Score', 'Trả pass/fail với findings theo severity.']],
    output: 'Blocking review report. Critical findings chặn completion.',
    avoid: 'Không dùng như bước polish/tóm tắt. Review phải cố phá change.',
    next: '/cf:sync sau khi fix và verification sạch',
  },
  sync: {
    title: 'Sync',
    command: '/cf:sync',
    category: 'State',
    summary: 'Đồng bộ Status và inline Receipt đã quan sát được, không bịa proof.',
    when: ['Task Status cần phản ánh fresh proof.', 'Inline Receipt stale hoặc thiếu.', 'Cần audit phẫu thuật giữa plan và flat task state.'],
    flow: [['Resolve', 'Xác định feature, flat task, observed state và exact proof command.'], ['Inspect', 'Đọc plan.md, task Status và final inline Receipt.'], ['Proof gate', 'Từ chối done nếu thiếu current runtime-derived proof.'], ['Sync', 'Chỉ update Status và canonical Receipt đã quan sát.'], ['Audit', 'Báo mismatch mà không bịa approval hay execution.']],
    output: 'Flat task đã đồng bộ với một Status và một inline Receipt hiện tại.',
    avoid: 'Không mark done từ chat memory hoặc khi task file chưa có evidence.',
    next: 'Docs checkpoint hoặc next unblocked task',
  },
  debug: {
    title: 'Debug',
    command: '/cf:debug',
    category: 'Diagnosis',
    summary: 'Workflow diagnosis-only, tự điều chỉnh độ sâu cho lỗi local và incident phức tạp.',
    when: ['Chưa biết root cause.', 'Test, build, CI job, UI flow, hoặc production behavior fail.', 'Cần evidence trước khi sửa code.'],
    flow: [['Scout', 'Map affected files, callers, runtime, config, tests, recent changes.'], ['Evidence', 'Capture failing baseline; incident sâu có timeline tương quan nhiều nguồn.'], ['Eliminate', 'Test competing causes và giữ lý do loại hoặc giữ từng giả thuyết.'], ['Trace', 'Tách trigger, root cause, contributing factors tới invariant do hệ thống sở hữu.'], ['Handoff', 'Định nghĩa blast radius, verification, side effects, và khoảng trống ngăn tái diễn.']],
    output: 'Diagnosis có evidence và proof plan ngăn tái diễn, sẵn sàng cho `/cf:fix`.',
    avoid: 'Không sửa product code trong lúc diagnosis, trừ temporary instrumentation đã remove trước handoff.',
    next: '/cf:fix',
  },
  fix: {
    title: 'Fix',
    command: '/cf:fix',
    category: 'Repair',
    summary: 'Luồng sửa lỗi thích ứng sau diagnosis, từ lỗi local nhanh đến incident có kiểm soát.',
    when: ['Root cause đã được xác định.', 'Bug cần repair an toàn, bám đúng nguyên nhân.', 'Incident production cần sửa theo stage và regression proof.'],
    flow: [['Evidence', 'Bắt đầu từ debug contract hoàn chỉnh hoặc diagnosis trước.'], ['Bound', 'Với lỗi không trivial, khóa outcome, constraints, non-goals và acceptance.'], ['Route', 'Chỉ research, brainstorm và plan sau diagnosis khi thật sự cần.'], ['Fix', 'Sửa nguyên nhân thật, không che symptom.'], ['Verify', 'Chạy lại reproduction, blast-radius checks và prevention proof.']],
    output: 'Repair có phạm vi rõ, before/after proof và residual risk minh bạch.',
    avoid: 'Không dùng cho speculative refactor, feature work hoặc symptom patch.',
    next: '/cf:test và /cf:code-review',
  },
  docs: {
    title: 'Docs',
    command: '/cf:docs',
    category: 'Documentation',
    summary: 'Tạo, refresh, summarize, hoặc reconstruct project documentation từ source code.',
    when: ['Docs thiếu hoặc stale.', 'Code change ảnh hưởng architecture, commands, deployment, onboarding.', 'Legacy system cần source-backed as-is documentation.'],
    flow: [['Mode', 'Chọn init, update, summarize, hoặc reconstruct.'], ['Scout', 'Đọc source, config, commands, architecture, docs root.'], ['Write', 'Update living docs hoặc build docs/as-is cho bounded scope.'], ['Uncertainty', 'Track assumptions, unknowns, evidence.'], ['Validate', 'Chạy docs validators trước handoff.']],
    output: 'Documentation bám current source behavior.',
    avoid: 'Không bịa architecture claim nếu không back được bằng files, commands, hoặc runtime evidence.',
    next: '/cf:specs cho modernization work, hoặc release handoff',
  },
  scout: {
    title: 'Scout',
    command: '/cf:scout',
    category: 'Discovery',
    summary: 'Codebase discovery nhanh cho file finding, task context, entrypoints, call paths, và blast radius.',
    when: ['Relevant files chưa rõ.', 'Task chạm nhiều directories.', 'Debugging, implementation, hoặc review cần scoped context.'],
    flow: [['Scope gate', 'Tránh root-wide scans và no-scan paths.'], ['Fast path', 'Dùng local search và targeted reads cho scope rõ.'], ['Delegate', 'Chỉ dùng Explore khi user cho phép, runtime hỗ trợ, và scopes độc lập.'], ['Aggregate', 'Trả files, call paths, integration points, risks, next steps.']],
    output: 'Context map gọn để follow-up work an toàn hơn.',
    avoid: 'Không scan secrets, build outputs, node_modules, .git, hoặc cả repo khi bounded scope là đủ.',
    next: 'Skill nhỏ nhất phù hợp với task đã discover',
  },
  git: {
    title: 'Git',
    command: '/cf:git',
    category: 'Release',
    summary: 'Branch, commit, push, PR, finish, và worktree operations an toàn với secret scanning và focused commits.',
    when: ['Verified changes sẵn sàng commit hoặc publish.', 'Cần focused conventional commit.', 'Parallel work cần isolated worktree.'],
    flow: [['Status', 'Inspect branch, staged diff, unstaged diff, intended action.'], ['Secret scan', 'Từ chối commit chứa keys, tokens, passwords, credentials.'], ['Split', 'Giữ commit focused và conventional khi cần.'], ['Publish', 'Commit, push, hoặc mở PR an toàn.'], ['Finish', 'Đưa lựa chọn merge, PR, keep, discard sau verification.']],
    output: 'Version-control history sạch, không leak secrets hoặc overwrite unrelated work.',
    avoid: 'Không force-push, delete worktrees, hoặc discard changes nếu chưa có xác nhận rõ.',
    next: 'Push, PR, hoặc branch finish flow',
  },
};
