import { SkillDetailMap } from './skill-detail-types';

export const skillDetailsJa: SkillDetailMap = {
  ask: {
    title: 'Ask',
    command: '/cf:ask',
    category: 'Consultation',
    summary: 'Source code、docs、specs、config、dependencies、external technical topics に対する evidence-backed Q&A skill。',
    when: ['現在の system behavior や flow を理解したい。', 'Planning や code change の前に source-backed answer が必要。', 'Repo evidence が不足し、current external docs も確認する必要がある。'],
    flow: [['Classify', 'Code behavior、config、specs、dependencies、workflow、external knowledge のどれかを判定します。'], ['Scout', 'README、docs、specs、code、config、tests、package metadata を先に読みます。'], ['Research', 'Repo evidence が不足または version-sensitive な場合だけ external/current sources を使います。'], ['Answer', 'Confirmed facts と inference を分け、evidence を示します。'], ['Ask back', 'そのまま答えると誤解を招く場合のみ、focused question を1つ返します。']],
    output: 'Evidence、confidence、gaps、必要な next step を含む直接回答。',
    avoid: 'Implement、scaffold、product code 編集、spec 作成、inference を confirmed fact と扱うことは禁止。',
    next: '回答内容に応じて /cf:brainstorm、/cf:specs、/cf:docs、または /cf:debug',
  },
  brainstorm: {
    title: 'Brainstorm',
    command: '/cf:brainstorm',
    category: 'Discovery',
    summary: 'Spec が存在する前の scout-first ideation です。raw intent を implementation code ではなく spec-ready decisions に変えます。',
    when: ['Request が曖昧または広すぎる。', 'Architecture choices がまだ開いている。', 'Spec に入る前に scope gates、risks、tradeoffs が必要。'],
    flow: [['Scout', 'Repo または relevant context を先に inspect します。'], ['Frame', 'Problem、user value、constraints、non-goals、risks を定義します。'], ['Compare', '単純な architecture options と tradeoffs を比較します。'], ['Decide', 'Spec-ready decisions と open questions を出します。'], ['Handoff', '方向が明確になってから specs に進みます。']],
    output: '`/cf:specs` に渡せる focused product and architecture direction。',
    avoid: 'Code、scaffold、未承認の implementation choice を作るためには使いません。',
    next: '/cf:specs',
  },
  specs: {
    title: 'Specs',
    command: '/cf:specs',
    category: 'Specification',
    summary: 'Reviewed process-first plan、flat executable tasks、C1/C2 の human decisions を作ります。',
    when: ['Direction が requirements に変換できるほど明確。', 'Coding の前に task files が必要。', 'Feature に traceable scope と evidence gates が必要。'],
    flow: [['C1', 'Outcome、scope、exclusions、constraints、未解決 choices を確認。'], ['Evidence', 'Decision に必要な findings を記録。'], ['Plan', 'Acceptance criteria と boundaries を持つ plan.md を作成。'], ['Tasks', 'Ownership、dependencies、proof commands を持つ flat task-NN files を作成。'], ['C2', 'Material review findings を human decision に提示。']],
    output: 'Reviewed `plan.md` と flat `task-NN-*.md`。新しい explicit develop invocation に ready。',
    avoid: 'Code を推測した後の飾りとして spec を作りません。Spec は implementation を制約するものです。',
    next: '/cf:develop',
  },
  develop: {
    title: 'Develop',
    command: '/cf:develop',
    category: 'Implementation',
    summary: 'Approved task packets を scope fidelity、task-aware inspection、verification、review、state sync とともに実装します。',
    when: ['Spec または task packet が approve 済み。', '1 task を安全に実装したい。', 'Task に completion criteria と evidence expectations がある。'],
    flow: [['Load', 'plan.md を開き、one unblocked flat task を選びます。'], ['Extract', 'Outcome、ownership、dependencies、acceptance、proof commands を読みます。'], ['Scout', 'Real entrypoints、callers、patterns、blast radius を trace。'], ['Implement', 'Justified scope escape 以外は active task boundary だけ変更。'], ['Verify', 'Exact planned command を実行し current output を取得。'], ['Receipt', 'Controller が single Status と final inline Receipt を更新。']],
    output: 'Reachable production code、task evidence、synchronized state。',
    avoid: 'Spec approval 前、または named technologies を placeholder に置き換えるためには使いません。',
    next: '/cf:test and /cf:code-review',
  },
  test: {
    title: 'Test',
    command: '/cf:test',
    category: 'Verification',
    summary: 'Real verification を実行し、green-looking command を proof と誤認せず concrete verdict を返します。',
    when: ['Implementation が behavior を変更した。', 'Blast-radius、full-suite、spec-aware、UI verification が必要。', 'Task が done になる前に evidence が必要。'],
    flow: [['Detect', 'Test runner と relevant commands を見つけます。'], ['Scope', 'blast-radius、full-suite、spec-aware、UI mode を選びます。'], ['Execute', 'Real lint、type、build、test、UI checks を実行します。'], ['Compare', 'Results を requirements、design contracts、evidence、reachability と比較します。'], ['Verdict', 'PASS、FAIL、PARTIAL、NO_TESTS と next action を返します。']],
    output: 'Commands、outcomes、failures、coverage、必要なら reachability notes を含む test verdict。',
    avoid: 'NO_TESTS、skipped tests、弱めた assertions、zero executed tests を pass と扱いません。',
    next: '/cf:code-review',
  },
  'code-review': {
    title: 'Code Review',
    command: '/cf:code-review',
    category: 'Review',
    summary: 'Spec compliance、code quality、security、regressions、contract drift を見る findings-first review。',
    when: ['Diff が review ready。', 'Done にする前に adversarial pass が必要。', 'PR、commit、path、feature scope に risk analysis が必要。'],
    flow: [['Target', 'Pending diff、commit、PR、path、feature scope を load します。'], ['Spec compliance', 'Missing requirements、extras、wrong runtime choices、unverified claims を確認します。'], ['Code quality', 'YAGNI、KISS、DRY、boundaries、naming、tests を review します。'], ['Adversarial pass', 'Security holes、races、edge cases、regressions を探します。'], ['Score', 'Severity 順 findings と pass/fail を返します。']],
    output: 'Blocking review report。Critical findings は completion を止めます。',
    avoid: 'Summary-only polish step として使いません。Change を壊しにいく review です。',
    next: 'Clean verification 後に /cf:sync',
  },
  sync: {
    title: 'Sync',
    command: '/cf:sync',
    category: 'State',
    summary: 'Observed process-first task Status と inline Receipt を proof の捏造なしで同期します。',
    when: ['Task Status が fresh proof を反映する必要がある。', 'Inline Receipt が stale または incomplete。', 'Plan と flat task state の surgical audit が必要。'],
    flow: [['Resolve', 'Feature、flat task、observed state、exact proof command を特定。'], ['Inspect', 'plan.md、task Status、final inline Receipt を読む。'], ['Proof gate', 'Current runtime-derived proof がない done を拒否。'], ['Sync', 'Observed Status と canonical Receipt だけを更新。'], ['Audit', 'Approval や execution を捏造せず mismatch を報告。']],
    output: 'One Status と one current inline Receipt を持つ synchronized flat task。',
    avoid: 'Chat memory だけ、または task file に evidence がない状態で done にしません。',
    next: 'Docs checkpoint または next unblocked task',
  },
  debug: {
    title: 'Debug',
    command: '/cf:debug',
    category: 'Diagnosis',
    summary: 'Local failures と complex incidents のための adaptive-depth、diagnostic-only root-cause workflow。',
    when: ['Root cause が不明。', 'Test、build、CI job、UI flow、production behavior が fail している。', 'Code change 前に evidence が必要。'],
    flow: [['Scout', 'Affected files、callers、runtime、config、tests、recent changes を map します。'], ['Evidence', 'Failing baseline を capture し、deep incident では cross-source timeline を追加します。'], ['Eliminate', 'Competing causes を検証し、各 candidate を残す・除く理由を記録します。'], ['Trace', 'Trigger、root cause、contributing factors を earliest owned invariant まで分離します。'], ['Handoff', 'Blast radius、verification、side effects、recurrence-prevention gaps を定義します。']],
    output: '`/cf:fix` に渡せる evidence-backed diagnosis と prevention-aware proof plan。',
    avoid: 'Diagnosis 中に product code を修正しません。Temporary instrumentation は handoff 前に remove します。',
    next: '/cf:fix',
  },
  fix: {
    title: 'Fix',
    command: '/cf:fix',
    category: 'Repair',
    summary: 'diagnosis 後の adaptive evidence-backed repair。local fix から bounded incident まで対応します。',
    when: ['root cause が特定済み。', 'bug に safe で cause-aligned な repair が必要。', 'production incident に staged regression proof が必要。'],
    flow: [['Evidence', 'complete debug contract から開始するか、先に diagnosis。'], ['Bound', 'non-trivial work では outcome、constraints、non-goals、acceptance を固定。'], ['Route', '必要な場合だけ diagnosis 後に research、brainstorm、plan。'], ['Fix', 'symptom mask ではなく root cause を修正。'], ['Verify', 'reproduction、blast-radius checks、prevention proof を再実行。']],
    output: 'before/after proof と明示的な residual risk を持つ bounded repair。',
    avoid: 'speculative refactor、feature work、symptom-only patch には使用しません。',
    next: '/cf:test and /cf:code-review',
  },
  docs: {
    title: 'Docs',
    command: '/cf:docs',
    category: 'Documentation',
    summary: 'Source code から project documentation を create、refresh、summarize、reconstruct します。',
    when: ['Docs が missing または stale。', 'Code change が architecture、commands、deployment、onboarding に影響する。', 'Legacy system に source-backed as-is documentation が必要。'],
    flow: [['Mode', 'init、update、summarize、reconstruct を選びます。'], ['Scout', 'Source、config、commands、architecture、docs root を読みます。'], ['Write', 'Living docs を update、または bounded scope の docs/as-is を作ります。'], ['Uncertainty', 'Assumptions、unknowns、evidence を track します。'], ['Validate', 'Handoff 前に docs validators を実行します。']],
    output: 'Current source behavior に grounded な documentation。',
    avoid: 'Files、commands、runtime evidence で back できない architecture claims を作りません。',
    next: 'Modernization work は /cf:specs、または release handoff',
  },
  scout: {
    title: 'Scout',
    command: '/cf:scout',
    category: 'Discovery',
    summary: 'File finding、task context、entrypoints、call paths、blast radius のための fast codebase discovery。',
    when: ['Relevant files が不明。', 'Task が複数 directories にまたがる。', 'Debugging、implementation、review に scoped context が必要。'],
    flow: [['Scope gate', 'Root-wide scans と no-scan paths を避けます。'], ['Fast path', 'Focused scope は local search と targeted reads を使います。'], ['Delegate', 'User permission、runtime support、independent scopes が揃う時だけ Explore を使います。'], ['Aggregate', 'Files、call paths、integration points、risks、next steps を返します。']],
    output: 'Follow-up work を安全にする compact context map。',
    avoid: 'Secrets、build outputs、node_modules、.git、または bounded scope で足りるのに entire repo を scan しません。',
    next: 'Discovered task に合う smallest skill',
  },
  git: {
    title: 'Git',
    command: '/cf:git',
    category: 'Release',
    summary: 'Secret scanning と focused commits を含む safe branch、commit、push、PR、finish、worktree operations。',
    when: ['Verified changes を commit または publish できる。', 'Focused conventional commit が必要。', 'Parallel work に isolated worktree が必要。'],
    flow: [['Status', 'Branch、staged diff、unstaged diff、intended action を確認します。'], ['Secret scan', 'Keys、tokens、passwords、credentials を含む commit を拒否します。'], ['Split', '必要なら commit を focused and conventional に保ちます。'], ['Publish', 'Commit、push、PR を安全に行います。'], ['Finish', 'Verification 後に merge、PR、keep、discard choices を出します。']],
    output: 'Secrets を漏らさず unrelated work を壊さない clean version-control history。',
    avoid: 'Explicit confirmation なしに force-push、delete worktrees、discard changes をしません。',
    next: 'Push、PR、または branch finish flow',
  },
};
